# Generated by Django 3.2.6 on 2025-07-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Receive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=6)),
                ('p_temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('p_hum', models.DecimalField(decimal_places=2, max_digits=5)),
                ('move', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=5)),
                ('loc', models.TextField()),
                ('temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hum', models.DecimalField(decimal_places=2, max_digits=5)),
                ('light', models.DecimalField(decimal_places=2, max_digits=5)),
                ('snd', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
