# Generated by Django 3.2.6 on 2025-07-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_data_receive_created_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=10)),
                ('dateWtime_start', models.DateTimeField()),
                ('dateWtime_end', models.DateTimeField()),
                ('event_occured', models.CharField(max_length=10)),
                ('instructor', models.CharField(max_length=30)),
            ],
        ),
    ]
