from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('data/', views.data_view, name='data'),
    path('sensor/data/', views.sensor_data, name='sensor_data'),
    path('sensor/data/multi/', views.sensor_data_multi, name='sensor_data_multi'),
    path('charts/', views.chart_view, name='chart'),
    path('personal/', views.personal_view, name='personal'),
    path('events/integrated/', views.integrated_event_view, name='integrated_event'),
    path('event/data/', views.event_data, name='event_data'),
    path('event/sensor/data/', views.event_sensor_data, name='event_sensor_data'),
    path('predict/', views.prediction_view, name='prediction'),
    path('predict-future-values/', views.predict_future_values, name='predict_future_values'),
    path('alarm/', views.alarm_view, name='alarm'),
    path('set-alarm-thresholds/', views.set_alarm_thresholds, name='set_alarm_thresholds'),
    path('check-alarms/', views.check_alarms, name='check_alarms'),
    path('acknowledge-alarm/', views.acknowledge_alarm, name='acknowledge_alarm'),
    path('set-email/', views.set_email, name='set_email'),
    path('send-email/', views.send_email_notification, name='send_email'),
    path('clear-timer-flag/', views.clear_timer_flag, name='clear_timer_flag'),
    path('set-timer-flag/', views.set_timer_flag, name='set_timer_flag'),
    path('test-timer-start/', views.test_timer_start, name='test_timer_start'),
    path('personal-data-latest/', views.personal_data_latest, name='personal_data_latest'),
    path('set-alarm-state/', views.set_alarm_state, name='set_alarm_state'),
    path('clear-alarm-state/', views.clear_alarm_state, name='clear_alarm_state'),
    path('update-move-status/', views.update_move_status, name='update_move_status'),
]